In [638]:
import pandas as pd
import numpy as np
import re
from datetime import datetime as dt

In [639]:
fw_log = pd.read_csv(r"input_files\20230311_FW_LOG_1.log", sep=";")
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
fw_log.drop('Unnamed: 0', axis=1, inplace=True)

val1 = fw_log.columns
val2 = fw_log.iloc[0].to_list()
val3 = fw_log.iloc[1].to_list()

fw_log.drop([0, 1], axis=0, inplace=True)
new_header = [str(v1) + str(v2) + str(v3) for v1, v2, v3 in list(zip(val1, val2, val3))]
new_header = [re.sub(r"Unnamed: \d|YYYY/MM/DD|HH:MM:SS|nan", "", some_string) for some_string in new_header]
new_header = [re.sub(r" |\.", "", some_string) for some_string in new_header]
# new_header = [re.sub(r"t_acts|t_tots", "", some_string) for some_string in new_header]
# new_header = [re.sub(r"\.|\-", "_", some_string).lower() for some_string in new_header]
fw_log.columns = new_header

fw_log['Date'] = pd.to_datetime(fw_log["Date"] + " " + fw_log['Time'])
fw_log.drop('Time', axis=1, inplace=True)

print(len(fw_log))
print(fw_log.info())

# Resultados de operación.
fw_log.head()

1335
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1335 entries, 2 to 1336
Data columns (total 39 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   UserUnit             1335 non-null   object
 1   Date                 1335 non-null   datetime64[ns]
 2   ProgNo               1335 non-null   object
 3   ProgName             1335 non-null   object
 4   orderNo              1335 non-null   object
 5   DMCRetractor         1335 non-null   object
 6   DMCMGG               1335 non-null   object
 7   No-actpartstotal     1335 non-null   object
 8   0No-actpartsok       1335 non-null   object
 9   1positionturntable   1335 non-null   object
 10  2contactposmm        1335 non-null   object
 11  3planaritymm         1335 non-null   object
 12  4distancemm          1335 non-null   object
 13  fric1Max/MinnU/min   1335 non-null   object
 14  fric2Max/MinnU/min   1335 non-null   object
 15  upset1Max/MinnU/min  1335 non-null   object
 16  8angelposdegree      1335 non-null   object
 17  fric11s_actmm        1335 non-null   object
 18  fric21s_actmm        1335 non-null   object
 19  brakes_actmm         1335 non-null   object
 20  upset11s_actmm       1335 non-null   object
 21  upset2s_actmm        1335 non-null   object
 22  totals_totmm         1335 non-null   object
 23  fric12t_acts         1335 non-null   object
 24  fric22t_acts         1335 non-null   object
 25  brake1t_acts         1335 non-null   object
 26  upset12t_acts        1335 non-null   object
 27  upset21t_acts        1335 non-null   object
 28  brake_n0t_acts       1335 non-null   object
 29  total1t_tots         1335 non-null   object
 30  fric13t_ups          1335 non-null   object
 31  fric23t_ups          1335 non-null   object
 32  upset13t-ups         1335 non-null   object
 33  upset22t_ups         1335 non-null   object
 34  total2L_FPmm         1335 non-null   object
 35  forceclampX1kN       1335 non-null   object
 36  positionclampX1mm    1335 non-null   object
 37  total3NOKBCD-Code    1335 non-null   object
 38  lastcycles           1335 non-null   object
dtypes: datetime64[ns](1), object(38)
memory usage: 406.9+ KB
None

,UserUnit,Date,ProgNo,ProgName,orderNo,DMCRetractor,DMCMGG,No-actpartstotal,0No-actpartsok,1positionturntable,2contactposmm,3planaritymm,4distancemm,fric1Max/MinnU/min,fric2Max/MinnU/min,upset1Max/MinnU/min,8angelposdegree,fric11s_actmm,fric21s_actmm,brakes_actmm,upset11s_actmm,upset2s_actmm,totals_totmm,fric12t_acts,fric22t_acts,brake1t_acts,upset12t_acts,upset21t_acts,brake_n0t_acts,total1t_tots,fric13t_ups,fric23t_ups,upset13t-ups,upset22t_ups,total2L_FPmm,forceclampX1kN,positionclampX1mm,total3NOKBCD-Code,lastcycles
2,OperadorZF,2023-03-11 00:03:27,46,CIVIC 1st LH DOM SLL3,20230310,P34309474B*714231006800SG,34311248A006102212,1690766,727,4,124.556,0.016,-20.559,13992.179,10800.944,-18.788,181.429,0.067,0.152,0.589,0.367,0.16,1.335,0.03,0.1,0.224,0.04,0.25,0.3,0.962,0.006,0.002,0.002,0.024,29.221,22.8,11.45,0,16.258
3,OperadorZF,2023-03-11 00:03:38,46,CIVIC 1st LH DOM SLL3,20230310,P34309474B*71423100680012,34311248A006102212,1690767,728,5,124.536,0.036,-20.606,13989.479,10811.166,-75.213,181.258,0.068,0.16,0.611,0.368,0.146,1.351,0.03,0.1,0.226,0.04,0.25,0.3,0.968,0.004,0.002,0.002,0.02,29.185,22.9,11.455,0,805.864
4,OperadorZF,2023-03-11 00:03:49,46,CIVIC 1st LH DOM SLL3,20230310,P34309474B*714231006800K5,34311248A006102212,1690768,729,6,124.536,0.025,-20.573,13990.585,10811.786,-6.706,181.592,0.066,0.139,0.52,0.367,0.166,1.258,0.03,0.1,0.224,0.04,0.25,0.304,0.966,0.004,0.002,0.002,0.028,29.278,22.9,11.453,0,10.424
5,OperadorZF,2023-03-11 00:04:00,46,CIVIC 1st LH DOM SLL3,20230310,P34309474B*72023100690D31,34311248A006102212,1690769,730,1,124.516,0.032,-20.571,13988.594,10805.369,-68.53,181.685,0.067,0.161,0.58,0.366,0.151,1.326,0.03,0.1,0.226,0.04,0.25,0.304,0.972,0.004,0.002,0.002,0.022,29.19,22.9,11.447,0,11.097
6,OperadorZF,2023-03-11 00:04:12,46,CIVIC 1st LH DOM SLL3,20230310,P34309474B*72023100690D32,34311248A006102212,1690770,731,2,124.556,0.033,-20.577,13990.674,10813.689,-7.68,181.579,0.068,0.173,0.586,0.367,0.171,1.365,0.03,0.1,0.224,0.04,0.25,0.302,0.962,0.004,0.002,0.002,0.026,29.191,22.9,11.441,0,11.154

In [640]:
ma_log = pd.read_csv(r"input_files\20230311_MA_LOG_1.log", sep=";")

# ma_log.columns = [re.sub(' ', '', column) for column in ma_log.columns]
ma_log.columns = [re.sub('-|\.|\:| ', '', column) for column in ma_log.columns]

ma_log['date'] = pd.to_datetime(ma_log["date"] + " " + ma_log['time'])
ma_log.drop('time', axis=1, inplace=True)


print(len(ma_log))
print(ma_log.info())
# Chequeo ok nok
ma_log.head()

1147
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1147 entries, 0 to 1146
Data columns (total 15 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   date                    1147 non-null   datetime64[ns]
 1   typenumber              1147 non-null   int64
 2   typename                1147 non-null   object
 3   FWnumber                1147 non-null   int64
 4   DMCRetractor            1147 non-null   object
 5   DMCMGG                  1147 non-null   object
 6   ST02cleanlaserprogno    1147 non-null   int64
 7   ST02cleanlaserokstatus  1147 non-null   object
 8   ST03lasercamprogno      1147 non-null   int64
 9   ST03lasercamokstatus    1147 non-null   object
 10  ST04FWokstatus          1147 non-null   object
 11  ST05anglecamprogno      1147 non-null   int64
 12  ST05anglecamvalue       1068 non-null   object
 13  ST05anglecamokstatus    1147 non-null   object
 14  overallokstatus         1147 non-null   object
dtypes: datetime64[ns](1), int64(5), object(9)
memory usage: 134.5+ KB
None

,date,typenumber,typename,FWnumber,DMCRetractor,DMCMGG,ST02cleanlaserprogno,ST02cleanlaserokstatus,ST03lasercamprogno,ST03lasercamokstatus,ST04FWokstatus,ST05anglecamprogno,ST05anglecamvalue,ST05anglecamokstatus,overallokstatus
0,2023-11-03 00:35:03,46,CIVIC 1st LH DOM SLL3,1690953,P34309474B*72023100690DAW,34311248A006102212,1,OK,2,OK,OK,5,186.22,OK,OK
1,2023-11-03 00:35:15,46,CIVIC 1st LH DOM SLL3,1690954,P34309474B*72023100690DAX,34311248A006102212,1,OK,2,OK,OK,5,182.98,OK,OK
2,2023-11-03 00:35:26,46,CIVIC 1st LH DOM SLL3,1690955,P34309474B*72023100690DAT,34311248A006102212,1,OK,2,OK,OK,5,182.65,OK,OK
3,2023-11-03 00:35:55,46,CIVIC 1st LH DOM SLL3,1690956,P34309474B*72023100690DAY,34311248A006102212,1,OK,2,OK,OK,5,184.3 D,OK,OK
4,2023-11-03 00:36:14,46,CIVIC 1st LH DOM SLL3,1690957,P34309474B*72023100690DB5,34311248A006102212,1,OK,2,OK,OK,5,182.60,OK,OK

In [641]:
paralog = pd.read_csv(r"input_files\ParaLog_20230311.txt", sep=';', encoding='unicode_escape')

paralog_header = ['date', 'hour', 'access_level', 'type', 'parameter', 'parameter_idk', 'change_to', 'unit', 'user']

paralog.drop(paralog.columns[[2, 4,6, 9, 12]], axis=1, inplace=True)

paralog.loc[-1] = paralog.columns
paralog.index = paralog.index + 1
paralog = paralog.sort_index()
paralog.columns = paralog_header

paralog['hour'] = paralog['hour'].str.replace("at ", "")

paralog['date'] = pd.to_datetime(paralog["date"] + " " + paralog['hour'])
paralog.drop('hour', axis=1, inplace=True)


print(len(paralog))
print(paralog.info())

# paralog.to_csv('paralog.csv')
# Ajustes de la máquina
paralog.head()

528
<class 'pandas.core.frame.DataFrame'>
Int64Index: 528 entries, 0 to 527
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   date           528 non-null    datetime64[ns]
 1   access_level   528 non-null    object
 2   type           528 non-null    object
 3   parameter      528 non-null    object
 4   parameter_idk  528 non-null    object
 5   change_to      528 non-null    object
 6   unit           528 non-null    object
 7   user           45 non-null     object
dtypes: datetime64[ns](1), object(7)
memory usage: 37.1+ KB
None

,date,access_level,type,parameter,parameter_idk,change_to,unit,user
0,2023-11-03 01:35:04,5,46,parameter for setpoint camers mgg threshold a...,mgg_threshold_angel,12,[°],OperadorZF
1,2023-11-03 01:35:28,5,46,parameter for setpoint camers mgg threshold a...,mgg_threshold_angel,10.0,[°],OperadorZF
2,2023-11-03 10:10:15,2,45,parameter for raw part pat down force setpoint,Ch1_R0218,2.0,[kN],ZapataF
3,2023-11-03 10:10:18,2,45,parameter for force pat down before process s...,Ch1_R0356,15.0,[kN],ZapataF
4,2023-11-03 10:22:06,2,45,parameter for liftingt: distance,Ch1_R0124,0.6,[mm],ZapataF

In [642]:
fw_ma = pd.merge(fw_log, ma_log, on=['DMCRetractor', 'DMCMGG'])

# fw_ma.to_csv('test.csv')


fw_ma.head()

,UserUnit,Date,ProgNo,ProgName,orderNo,DMCRetractor,DMCMGG,No-actpartstotal,0No-actpartsok,1positionturntable,2contactposmm,3planaritymm,4distancemm,fric1Max/MinnU/min,fric2Max/MinnU/min,upset1Max/MinnU/min,8angelposdegree,fric11s_actmm,fric21s_actmm,brakes_actmm,upset11s_actmm,upset2s_actmm,totals_totmm,fric12t_acts,fric22t_acts,brake1t_acts,upset12t_acts,upset21t_acts,brake_n0t_acts,total1t_tots,fric13t_ups,fric23t_ups,upset13t-ups,upset22t_ups,total2L_FPmm,forceclampX1kN,positionclampX1mm,total3NOKBCD-Code,lastcycles,date,typenumber,typename,FWnumber,ST02cleanlaserprogno,ST02cleanlaserokstatus,ST03lasercamprogno,ST03lasercamokstatus,ST04FWokstatus,ST05anglecamprogno,ST05anglecamvalue,ST05anglecamokstatus,overallokstatus
0,OperadorZF,2023-03-11 00:53:58,46,CIVIC 1st LH DOM SLL3,20230310,P34309474B*72023100690DAW,34311248A006102212,1690952,913,4,124.456,0.024,-20.568,13993.949,10821.699,-0.422,181.557,0.068,0.131,0.499,0.363,0.169,1.23,0.03,0.1,0.222,0.04,0.25,0.3,0.98,0.006,0.002,0.002,0.026,29.226,22.9,11.452,0,11.107,2023-11-03 00:35:03,46,CIVIC 1st LH DOM SLL3,1690953,1,OK,2,OK,OK,5,186.22,OK,OK
1,OperadorZF,2023-03-11 00:54:10,46,CIVIC 1st LH DOM SLL3,20230310,P34309474B*72023100690DAX,34311248A006102212,1690953,914,5,124.427,0.034,-20.524,13994.48,10821.301,-2.369,181.431,0.067,0.158,0.62,0.367,0.163,1.375,0.03,0.1,0.22,0.04,0.25,0.296,0.984,0.006,0.002,0.002,0.024,29.052,23,11.455,0,11.124,2023-11-03 00:35:15,46,CIVIC 1st LH DOM SLL3,1690954,1,OK,2,OK,OK,5,182.98,OK,OK
2,OperadorZF,2023-03-11 01:48:53,46,CIVIC 1st LH DOM SLL3,20230311,P34309474B*72023100690DAT,34311248A006102212,1690954,915,6,124.356,0.013,-20.606,13989.214,10785.454,-79.196,181.519,0.069,0.139,0.583,0.366,0.15,1.307,0.03,0.1,0.226,0.04,0.25,0.302,1.004,0.006,0.002,0.002,0.02,29.049,22.8,11.463,0,167.986,2023-11-03 00:35:26,46,CIVIC 1st LH DOM SLL3,1690955,1,OK,2,OK,OK,5,182.65,OK,OK
3,OperadorZF,2023-03-11 01:49:05,46,CIVIC 1st LH DOM SLL3,20230311,P34309474B*72023100690DAY,34311248A006102212,1690955,916,1,124.406,0.024,-20.591,13991.072,10789.481,-76.718,181.403,0.067,0.131,0.581,0.367,0.149,1.295,0.03,0.1,0.222,0.04,0.25,0.296,0.99,0.006,0.002,0.002,0.02,29.111,22.9,11.463,0,296.608,2023-11-03 00:35:55,46,CIVIC 1st LH DOM SLL3,1690956,1,OK,2,OK,OK,5,184.3 D,OK,OK
4,OperadorZF,2023-03-11 01:49:16,46,CIVIC 1st LH DOM SLL3,20230311,P34309474B*72023100690DB5,34311248A006102212,1690956,917,2,124.396,0.03,-20.597,13988.682,10787.092,-32.153,181.576,0.068,0.111,0.477,0.363,0.169,1.19,0.03,0.1,0.22,0.04,0.25,0.298,0.99,0.006,0.002,0.002,0.024,29.207,22.9,11.459,0,296.608,2023-11-03 00:36:14,46,CIVIC 1st LH DOM SLL3,1690957,1,OK,2,OK,OK,5,182.60,OK,OK

In [643]:
test = paralog.groupby('parameter').size().reset_index(name='count')
test.sort_values('count', ascending=False).head(5)

                                           parameter  count
235       parameter for upsetting 1: set value force     11
124        parameter for friction 1: set value force     11
248       parameter for upsetting 2: set value force     11
137        parameter for friction 2: set value force      9
149   parameter for raw part pat down force setpoint      4

In [644]:
start_date = dt.strptime("11/3/2023  12:01:00 PM", '%m/%d/%Y %I:%M:%S %p')
end_date = dt.strptime("11/3/2023  1:11:00 PM", '%m/%d/%Y %I:%M:%S %p')
parameters = [
    'parameter for friction 1: set value force',
    'parameter for friction 2: set value force',
    'parameter for upsetting 1: set value force',
    'parameter for upsetting 2: set value force']

paralog = paralog[paralog['parameter'].str.contains('value force')]
paralog = paralog.loc[(paralog['date'] >= start_date) & (paralog['date'] <= end_date)]

print(len(paralog))
paralog.head(3)

34

,date,access_level,type,parameter,parameter_idk,change_to,unit,user
19,2023-11-03 12:02:25,2,45,parameter for friction 1: set value force,Ch1_R0135,9.0,[kN],ZapataF
20,2023-11-03 12:02:28,2,45,parameter for upsetting 1: set value force,Ch1_R0155,9.0,[kN],ZapataF
21,2023-11-03 12:02:30,2,45,parameter for upsetting 2: set value force,Ch1_R0165,9.0,[kN],ZapataF

In [645]:

fw_ma = fw_ma.loc[
    (fw_ma['Date'] >= dt.strptime("3/11/2023  12:01:00 PM", '%m/%d/%Y %I:%M:%S %p')) &
    (fw_ma['Date'] <= dt.strptime("3/11/2023  1:11:00 PM", '%m/%d/%Y %I:%M:%S %p'))
]

fw_ma.head(3)

,UserUnit,Date,ProgNo,ProgName,orderNo,DMCRetractor,DMCMGG,No-actpartstotal,0No-actpartsok,1positionturntable,2contactposmm,3planaritymm,4distancemm,fric1Max/MinnU/min,fric2Max/MinnU/min,upset1Max/MinnU/min,8angelposdegree,fric11s_actmm,fric21s_actmm,brakes_actmm,upset11s_actmm,upset2s_actmm,totals_totmm,fric12t_acts,fric22t_acts,brake1t_acts,upset12t_acts,upset21t_acts,brake_n0t_acts,total1t_tots,fric13t_ups,fric23t_ups,upset13t-ups,upset22t_ups,total2L_FPmm,forceclampX1kN,positionclampX1mm,total3NOKBCD-Code,lastcycles,date,typenumber,typename,FWnumber,ST02cleanlaserprogno,ST02cleanlaserokstatus,ST03lasercamprogno,ST03lasercamokstatus,ST04FWokstatus,ST05anglecamprogno,ST05anglecamvalue,ST05anglecamokstatus,overallokstatus
1037,ZapataF,2023-03-11 12:07:27,45,CIVIC 1st LH DOM SLL3,20230311,P34361270A*714231006900YA,34311248A006102212,1691989,1,3,124.495,0.023,-20.566,13992.267,10789.57,-5.334,181.734,0.068,0.156,0.613,0.368,0.171,1.375,0.03,0.1,0.224,0.04,0.25,0.302,0.974,0.006,0.002,0.002,0.028,29.12,22.8,11.451,0,15.108,2023-11-03 10:55:32,45,CIVIC 1st LH DOM SLL3,1691990,1,OK,2,OK,OK,5,180.72,OK,OK
1038,ZapataF,2023-03-11 12:09:09,45,CIVIC 1st LH DOM SLL3,20230311,P34361270A*714231006900YD,34311248A006102212,1691990,2,4,124.514,0.019,-20.562,13992.798,10783.994,-61.273,181.383,0.067,0.184,0.663,0.37,0.154,1.439,0.03,0.1,0.222,0.04,0.25,0.296,0.968,0.006,0.002,0.002,0.022,29.076,22.8,11.453,0,34.244,2023-11-03 10:57:45,45,CIVIC 1st LH DOM SLL3,1691991,1,OK,2,OK,OK,5,181.13,OK,OK
1039,ZapataF,2023-03-11 12:09:23,45,CIVIC 1st LH DOM SLL3,20230311,P34361270A*714231006900YE,34311248A006102212,1691991,3,5,124.516,0.037,-20.564,13989.966,10797.403,-32.02,181.414,0.066,0.173,0.622,0.367,0.161,1.39,0.03,0.1,0.22,0.04,0.25,0.294,0.966,0.006,0.002,0.002,0.024,29.126,22.9,11.457,0,11.396,2023-11-03 11:01:58,45,CIVIC 1st LH DOM SLL3,1691993,1,OK,2,OK,OK,5,182.76,OK,OK

In [646]:
# fw_ma.to_csv('fw_ma.csv', index=False)
# paralog.to_csv('paralog.csv', index=False)